resolver: lts-13.25

packages:
- .
- location: ../easytest
  extra-dep: true
- location: ../odbc
  extra-dep: true

extra-deps:
- lens-errors-0.2.2.0

# ghc-options: {"$locals": -ddump-to-file -ddump-hi}